all:
	cd libcss; make; cd ..
	cd libparserutils; make; cd ..
	cd testcases-ryanc; make; cd ..

debug:
	cd libcss; make debug; cd ..
	cd libparserutils; make debug; cd ..
	cd testcases-ryanc; make debug; cd ..
run:
	cd libcss; make run; cd ..
	cd libparserutils; make run; cd ..
	cd testcases-ryanc; make run; cd ..

clean:
	cd libcss; make clean; cd ..
	cd libparserutils; make clean; cd ..
	cd testcases-ryanc; make clean; cd ..
