all:
	cd libcss; make; cd ..
	cd libparserutils; make; cd ..
	cd utils; make; cd ..

debug:
	cd libcss; make debug; cd ..
	cd libparserutils; make debug; cd ..
	cd utils; make debug; cd ..

run:
	cd libcss; make run; cd ..
	cd libparserutils; make debug; cd ..
	cd utils; make debug; cd ..

clean:
	cd libcss; make clean; cd ..
	cd libparserutils; make clean; cd ..
	cd utils; make clean; cd ..
