pub enum parserutils_error {
    PARSERUTILS_OK = 0,
    PARSERUTILS_BADPARAM = 1,
    PARSERUTILS_NOMEM = 2,
    PARSERUTILS_EOF = 3,
    PARSERUTILS_BADENCODING = 4,
    PARSERUTILS_NEEDDATA = 5,
    PARSERUTILS_INVALID = 6,
    PARSERUTILS_ICONV_ERROR = 8,
    PARSERUTILS_SUCCESS = 9
}