pub enum parserutils_error {
	PARSERUTILS_OK,
	PARSERUTILS_NOMEM,
	PARSERUTILS_BADPARM,
	PARSERUTILS_INVALID,
	PARSERUTILS_FILENOTFOUND,
	PARSERUTILS_NEEDDATA,
	PARSERUTILS_BADENCODING,
	PARSERUTILS_EOF
}