#! /bin/sh
rm -f *.so
cd parse/properties
rm -f autogenerated_properties.rs
rustc css_property_parser_gen.rs -o css_properties_parser_gen
./css_properties_parser_gen
cd -
rustc -L . -L ../libwapcaplet -L ../libparserutils css.rc
