#! /bin/sh
rm -f *.so
cd parse/properties
rm -f autogenerated.rs
rustc css_property_parser_gen.rs -o css_properties_parser_gen
./css_properties_parser_gen
rm -f css_properties_parser_gen
cd -
rustc -L ../libwapcaplet -L ../libparserutils css.rc
