#!/bin/bash


function Process1 {
	rm  -rf r_output.txt c_output.txt ;
	for i in {1..250}
	do
	   ./select-auto >> r_output.txt
	   ./test_select-auto data/select/tests1.dat >> c_output.txt
	done
}

function Process2 {
	rm  -rf r_output2.txt c_output2.txt ;
	for i in {1..250}
	do
	   ./select-auto >> r_output2.txt
	   ./test_select-auto data/select/tests1.dat >> c_output2.txt
	done
}

Process1 &

Process2

sleep 3

cat r_output2.txt >> r_output.txt
cat c_output2.txt >> c_output.txt

./test_data_avg

