pub enum css_result {
	CSS_OK  ,
	CSS_NOMEM,
	CSS_BADPARM,
	CSS_INVALID,
	CSS_FILENOTFOUND,
	CSS_NEEDDATA,
	CSS_BADCHARSET,
	CSS_EOF,
	CSS_IMPORTS_PENDING,
	CSS_PROPERTY_NOT_SET,
	CSS_SHOULD_NEVER_OCCUR
}
